---
title: "What went wrong?"
author: "Robert Gruener"
date due: "7/13/2020"
output: github_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

## HW02 Part A

### First load packages

```{r load libraries}
library("ggplot2")
library("magrittr") #so I can do some piping
```

### Graph 1

```{r}
data(mpg) #this is a dataset from the ggplot2 package

mpg %>% 
  ggplot(mapping = aes(x = city, y = hwy, color = "blue")) %>% 
  geom_point()

```
```{r}
data(mpg) #this is a dataset from the ggplot2 package

ggplot(mpg, mapping = aes(x = cty, y = hwy, color = "blue")) + 
  geom_point()
```

### Graph 2

```{r}
data("mpg")
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")

```



### Graph 3

```{r}
# graph without legend title
data("mpg")
ggplot(mpg, aes(displ, hwy, color = class)) + 
  # alpha designates opacity
  # size set to 2
  geom_point(alpha = 2, size = 2) +
  theme(legend.direction = "horizontal") + 
  theme(legend.position = c(0.6, 0.87)) +
  # remove legend title
  theme(legend.title = element_blank())

```
```{r}
# graph without legend
data("mpg")
ggplot(mpg, aes(displ, hwy, color = class)) + 
  # alpha designates opacity
  # size set to 2
  geom_point(alpha = 2, size = 2) +
  # remove legend
  theme(legend.position = "none")

```

### Graph 4

```{r}
mpg %>% 
ggplot(mapping = aes(x = displ, y = hwy)) + 
  # moving color to geom_point so that geom_smooth doesn't include it
  geom_point(aes(color = drv)) + 
  geom_smooth(se = F) #se = F makes it so it won't show the error in the line of fit
```
### Graph 5

```{r}
ggplot(data = mpg, mapping = aes(x = manufacturer, y = cty, color = manufacturer)) + 
  # specify boxplot color
  geom_boxplot(color = "black") + 
  # add a margin to axis labels
  theme(axis.text.x = element_text(angle = 45, margin = margin(12, 0, 12, 0)))
```


